Add window and mobile version popup
abreham1222/Microverse-portfolio pull request #21
Opened 2022-04-08 12:05 UTC by abreham1222

1. Added window popup for a desktop version
2. Added mobile version popup
3. Added linters for js
4. Added other images

2022-04-08 17:45 UTC, vic778 requested changes
## Hi @abreham1222 ,

Good job so far!

## Highlights!
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Good code organization ✔️
- All tests passed ✔️ 

Hello ✋, you have done well reaching this point of the project 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@victoir` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-08 17:45 UTC, vic778 commented on script.js
> +};
kindly all your projects should be implemented in your js file. you have to create an array that will contain all of your projects like projects = 
`[
   {
   },
  {
  },
  ....
] `

2022-04-08 17:45 UTC, vic778 commented on script.js
> +}
please make sure you're following the design of the project. [click here](https://github.com/abreham1222/Microverse-portfolio.git)to see the design of your Figma template. your see button should pop up the image with the description according the requirement of the project

2022-04-08 19:07 UTC, Davidosky007 reviewed
Hello @abreham1222 👋,

_This is an additional review as a result of the second opinion request._

Well done with all the hard work you guys have put into this milestone 👏 💪 

- Kindly note that this  `[ ]` is what represents an array and `{ }` is what wraps an object, according to the project requirement you should have an array of objects `[ { }, { }, .... ]` kindly add more project objects so that you can loop through it and render each on the page dynamically 👍 
- Also on the desktop the see project button doesn't  display a popup on click and on MObile some see project buttons also are not working.

Kindly 🙏 Fix these issues and submit another Code review request.
Please ask for another review in your Dashboard and the next Code Reviewer will review it accordingly 

Keep rocking 🚀!

2022-04-14 21:59 UTC, brytebee requested changes
Hi, @ 👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- All linter checks are installed and pass.✔️
- The popup button opens the modal and the **X** closes it. ✔️
- Design is responsive to screen size (mobile & desktop). ✔️
- Handled JS Array of Object correct and render data to the DOM dynamically. ✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-14 21:59 UTC, brytebee commented on popup.css
> +    padding-bottom: 5px;
- [ ] **Required:** You have done an amazing job so far. 👏 
However, there are some changes you need to make.

Your Design | Template
:---: | :---:
![image](https://user-images.githubusercontent.com/27709832/163481107-95ec5a1e-1c39-4fc1-9eb9-c4885fb496ec.png) | ![image](https://user-images.githubusercontent.com/27709832/163481331-bc3882e6-47e7-4888-9709-be76337f7dfc.png)

1. Your image overflows from the modal, kindly fix this.

2. Your modal has no contrast when popped up from the main page. It is better for UX and accessibility to have a contrast. Kindly make the main page dim when the modal is popped as illustrated in the template.

3. **Optional** You could consider reducing the height of the mobile modal and truncating the text to have a better UI design.

4. On the mobile pop-up, re-position the buttons to be more like the template, justify the text and dim the main page.

Your Design | Template
:---: | :---:
![image](https://user-images.githubusercontent.com/27709832/163483085-5e5827a3-f772-49ab-b8f3-bf3ed7aaa9e2.png) | ![image](https://user-images.githubusercontent.com/27709832/163483161-0a44d305-af79-4697-83f3-3cc1bd8bcd65.png)

2022-04-14 21:59 UTC, brytebee commented on script.js
> +    live.href = projectDetail.linklive;
- [ ] **Required:** Kindly fix these console errors.

![image](https://user-images.githubusercontent.com/27709832/163482446-bef0ca67-0637-4b1f-a122-a21470559ef6.png)

2022-04-15 06:49 UTC, CollinsTatang approved these changes
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 07:01 UTC, merged