Desktop version portfolio
abreham1222/Microverse-portfolio pull request #7
Opened 2022-03-24 18:29 UTC by abreham1222

Added the desktop version portfolio
1. Added index.html
2. Added style.css
3. Added importantly images
4. Added linters for GitHub actions

2022-03-24 20:00 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @abreham1222, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Good PR Title and Description

## Required 
- [ ] Add description in your readme for a better understanding of what the project is about.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 20:00 UTC, sja-thedude commented on style.css
>    display: flex;
- [ ] Kindly fix the mobile version contact form according to the figma design.
- Your design:
<img width="366" alt="Screenshot 2022-03-24 at 10 24 47 PM" src="https://user-images.githubusercontent.com/70269507/159996454-f3b2c712-641b-44f0-94a1-4539736e0bba.png">

- Figma design:
<img width="307" alt="Screenshot 2022-03-24 at 10 25 07 PM" src="https://user-images.githubusercontent.com/70269507/159996481-cd6638ee-c8d8-4c8e-a970-8fcbc9ef8be2.png">

2022-03-24 20:00 UTC, sja-thedude commented on style.css
> +  }
- [ ] Kindly fix the contact section of the desktop version.
- [ ] Kindly follow the spacing according to the Figma design.
- Your design:
<img width="1369" alt="Screenshot 2022-03-24 at 10 30 35 PM" src="https://user-images.githubusercontent.com/70269507/159996983-d6eb92ca-3b8a-4204-9032-d1fc88135b5a.png">

- Figma design:
<img width="993" alt="Screenshot 2022-03-24 at 10 33 21 PM" src="https://user-images.githubusercontent.com/70269507/159997028-f8a44421-9234-475a-82b2-76aebd9c53d9.png">

2022-03-24 20:00 UTC, sja-thedude commented on style.css
> +    font-style: normal;
- Kindly follow the spacing for your design according to the Figma design.
- Your design:
<img width="1369" alt="Screenshot 2022-03-24 at 10 32 22 PM" src="https://user-images.githubusercontent.com/70269507/159997504-627dbed1-8f39-47c3-a7b7-81959f46f7de.png">
<img width="1369" alt="Screenshot 2022-03-24 at 10 32 02 PM" src="https://user-images.githubusercontent.com/70269507/159997526-33376056-f975-4b0f-bb4c-a16bd66f84b5.png">
<img width="1369" alt="Screenshot 2022-03-24 at 10 31 51 PM" src="https://user-images.githubusercontent.com/70269507/159997535-2d339be8-e025-4a2d-bf7f-42ad6fc48e05.png">


- Figma design:
<img width="993" alt="Screenshot 2022-03-24 at 10 33 39 PM" src="https://user-images.githubusercontent.com/70269507/159997292-25538711-2004-4b45-a0be-c48405fdf40c.png">
<img width="993" alt="Screenshot 2022-03-24 at 10 33 54 PM" src="https://user-images.githubusercontent.com/70269507/159997306-d8ed5a23-a325-4e55-b43b-29d9d3243f1e.png">

2022-03-24 20:00 UTC, sja-thedude commented on index.html
> +          <h2 class="work">My Recent Works</h2>
- [ ] Kindly add a line below recent work for the mobile version, follow the spacing according to the Figma design.
- Your design:
<img width="303" alt="Screenshot 2022-03-24 at 10 27 45 PM" src="https://user-images.githubusercontent.com/70269507/159998379-ae001ac1-18b6-48a8-9904-fc92a531e54f.png">

- Figma design:
<img width="303" alt="Screenshot 2022-03-24 at 10 27 37 PM" src="https://user-images.githubusercontent.com/70269507/159998344-794215d8-4579-471c-a0fb-012cd3625177.png">

2022-03-24 20:00 UTC, sja-thedude commented on index.html
> +            <li class="pro-lis">bootstrap</li>
- [ ] Kindly fix the section of the mobile and desktop version, follow the spacing according to the Figma design.
- Your design:
<img width="364" alt="Screenshot 2022-03-24 at 10 26 07 PM" src="https://user-images.githubusercontent.com/70269507/159998962-d3970454-9dac-4908-bb7e-950e411db26e.png">

- Figma design:
<img width="303" alt="Screenshot 2022-03-24 at 10 26 25 PM" src="https://user-images.githubusercontent.com/70269507/159999011-d0fba5e0-2694-47c5-8798-bc5429934e66.png">

2022-03-24 21:27 UTC, abreham1222 commented on style.css
>    display: flex;
Please check it with a width of 375.
![375](https://user-images.githubusercontent.com/97598663/160012955-a169b5a3-ce68-4d36-b080-63f1cb7d7aa2.jpg)

2022-03-24 23:00 UTC, moise10r requested changes
Hi @abreham1222, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @moise10r when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 23:00 UTC, moise10r commented on index.html
> +          <hr>
- [ ] According to the requirement, you must stick to the design as much as possible (e.g., font, colors, images, tests, margins) using [the info of the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). Kindly use the same vertical line as in the Figma design


|| Your design |     Original design ||
 |-|---------|----------|-|
|-|![good4](https://user-images.githubusercontent.com/57562869/160023672-5331a427-f248-48b2-8515-f89bf40272cb.png) | ![bad4](https://user-images.githubusercontent.com/57562869/160023693-ecdbcb6a-a210-4dbe-a1f4-1a2058a8fd08.png)|-|

2022-03-24 23:33 UTC, abreham1222 commented on index.html
>             </p>
Please show me what was my mistake I can't see what is not working right?

https://user-images.githubusercontent.com/97598663/160026636-f9b6d972-c4c1-423f-870f-d78415e14990.mp4

2022-03-26 11:21 UTC, codepantherr requested changes
Hi @abreham1222 👋, 

Well done for your efforts in trying to implement the required changes 👏 👏 👏 
However, there are still some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/cYaB1VycDbOyOiXcCx/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-26 11:21 UTC, codepantherr commented on index.html
>             <ul class="icons">
- [ ] As requested by the previous reviewer, kindly make your form look like the one in the Figma design 🙏 
### Your design: 
![image](https://user-images.githubusercontent.com/46839548/160236841-70f4514c-4404-45b7-bf4f-c9d2131dfa7c.png)
### Figma design
![image](https://user-images.githubusercontent.com/46839548/160236856-3f5f19e2-a847-4443-a9ca-eb61a040e5f1.png)

2022-03-26 11:21 UTC, codepantherr commented on index.html
>             <ul class="icons">
- [ ] Please add a horizontal line above your social media icons as requested by the previous reviewer. Take a look at the Figma design to understand what is required of you. 👍 
Your design:
![image](https://user-images.githubusercontent.com/46839548/160236728-5c5dc8a5-2615-4c0e-a452-0b871ec7a09e.png)
Figma design:
![image](https://user-images.githubusercontent.com/46839548/160236753-c29c7729-1e7f-427f-91b6-7cdce1ad6c9e.png)

2022-03-26 11:21 UTC, codepantherr commented on style.css
> +  box-sizing: border-box;
- [ ] Your desktop version now has a horizontal scrolling bar which is not good for user experience. This happened because you removed the `overflow-x: hidden;` line from your CSS. Kindly put it back there to make it display correctly 🙏 
![image](https://user-images.githubusercontent.com/46839548/160237005-d5bcc057-27fa-409e-ad90-b41cfe2cdbed.png)

2022-03-26 11:32 UTC, abreham1222 commented on style.css
> +  box-sizing: border-box;
Kindly when I use the overflow-x: hidden it is not shrink the grid cards.

2022-03-26 14:05 UTC, sinansevgi reviewed
Hello @abreham1222  👋,

_This is an additional review as a result of the second opinion request._

I can see the horizontal scroll problem already and you have added the desired horizontal line to the footer :+1: 

As this was the only reason that your project was not approved it will be approved as soon as possible. 
Please note that since we will approve it manually so this could take few hours!

Keep rocking 🚀!
Sinan Sevgi

2022-03-26 15:47 UTC, merged